language: php

php: 
  - 5.3
  - 5.4

env:
  global:
    - CI_HOME=`pwd`/kort/kort-home
    - BUILD_DIR=`pwd`/build_heroku
    - secure: "NHfJqIEWAwVFC6hq6FSDpxxf3TqlIkJxxwNqkgQ/IgvodAoHQfIgVNW91wV6\nHjMgpVDRWTtcj3Xb5a0E2zKHKWu89LfwCAwQLF6vbdqwsgGbZd2jrAh63QQK\n2HMIWdr8UHdrqaL8sQ+fXlPRarAHh7yGRFL4RyhIQAKU/ZX7nU0="

before_script:
  - gem install sass
  - gem install compass
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh >/dev/null 2>&1
  - export PATH="$PATH:$CI_HOME:/usr/local/heroku/bin"
  - curl -s http://getcomposer.org/installer | php --
  - php composer.phar install --dev
  - phpenv rehash

script: ant build

after_script:
  - bash $CI_HOME/heroku/heroku.sh
